## Pandas Nedir, Özellikler

* NumPy'ın alternatifi değildir, NumPy'ın özelliklerini kullanan ve bu özellikleri genişleten bir kütüphanedir.
* NumPy'dan farklı olarak yapay veri setleri ile daha esnek çalışmaya izin veriyor.
* Pandas veri manipülasyonu ve veri analizi için yazılmış açık kaynak kodlu bir kütüphanedir.
* Ekonometrik DataFrame yapısını Python'a getirmiş oldu.

## Pandas Serisi Oluşturmak

* Pandas serisini tek boyutlu array olarak düşünebiliriz. 

In [1]:
import pandas as pd

In [2]:
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

* Yukarıda görülen çıktıda sol taraftaki değerler index bilgisini tutarken, sağ taraftaki değerler ise listenin elemanlarıdır

In [6]:
type(pd.Series([1, 2, 3, 4])) #type bilgisine ulaşıyoruz.

pandas.core.series.Series

In [7]:
pd.Series([1, 2, 3, 4]).axes

[RangeIndex(start=0, stop=4, step=1)]

* Axes komutu ile de serimizin başlangıç, bitiş ve artış değerlerinin bilgilerini alabiliyoruz.

In [8]:
pd.Series([1, 2, 3, 4]).dtype

dtype('int64')

* dtype komutu ile serimizin veri tipi hakkında bilgi verir.

In [10]:
pd.Series([1, 2, 3, 4]).size

4

* size komutu ile serimizin eleman sayısını öğrenebiliriz.

In [12]:
pd.Series([1, 2, 3, 4]).ndim

1

* ndim komutu ile serimizin boyutunu öğrenebiliriz.

In [14]:
pd.Series([1, 2, 3, 4]).values

array([1, 2, 3, 4], dtype=int64)

* values komutu ile serimizin index bilgileri olmadan da sadece değerlerini tutan bir liste gibi gösterebiliriz.

In [16]:
pd.Series([1, 2, 3, 4]).head(2)

0    1
1    2
dtype: int64

* head komutu ile serimizin baştan başlayarak kaç elemanını görmeyi istiyorsak verdiğimiz parametle ile bunu gerçekleştirebiliyoruz.

In [17]:
pd.Series([1, 2, 3, 4]).tail(3)

1    2
2    3
3    4
dtype: int64

* tail komutu ile de head komutunda yaptığımızın tersini yapabiliyoruz, serinin sonundan başlayarak kaç elemana erişmek istiyorsak buna ulaşabiliyoruz.

## Index İsimlendirme

In [19]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

* Yukarıdaki çıktı da indexler default olarak 0'dan başlayarak 1'er artarak devam ediyor, bunu değiştirmek için;

In [20]:
pd.Series([1, 2, 3, 4, 5], index = [10, 12, 14, 16, 18])

10    1
12    2
14    3
16    4
18    5
dtype: int64

* Yukarıda da gördüğümüz gibi index değerlerini el ile girerek istediğimiz değerleri verebiliriz. Index'leri string'ler ile de kullanabiliriz.
* Aynı zamanda indexlemeyi string ile yaparsak sözlük yapısından da kullandığımız key-value çalışmalarını yapabiliriz.

In [22]:
seri = pd.Series([1, 2, 3, 4, 5], index = ["a", "b", "c", "d", "e"])
seri

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [23]:
seri["c"]

3

* Slice işlemlerini de burada kullanabiliriz, örneğin;

In [24]:
seri["b":]

b    2
c    3
d    4
e    5
dtype: int64

In [25]:
seri["a":"c"]

a    1
b    2
c    3
dtype: int64

## Sözlük Üzerinden Seri Oluşturmak

In [28]:
sozluk = {"ad" : "Selman", "soyad" : "Başkaya", "yaş" : 21}
seri =pd.Series(sozluk)
seri

ad        Selman
soyad    Başkaya
yaş           21
dtype: object

## İki Farklı Seriyi Birleştirerek Tek Bir Seri Oluşturma

In [29]:
pd.concat([seri, seri])

ad        Selman
soyad    Başkaya
yaş           21
ad        Selman
soyad    Başkaya
yaş           21
dtype: object

## Eleman İşlemleri

* NumPy üzerinden oluşturulan listeyi pandas serisine çevirmek;

In [30]:
import numpy as np
a = np.array([1, 3, 5, 6, 8])
seri = pd.Series(a)
seri

0    1
1    3
2    5
3    6
4    8
dtype: int32

In [32]:
seri = pd.Series([145, 170, 187, 163], index = ["reg", "loj", "cart", "rf"])
seri

reg     145
loj     170
cart    187
rf      163
dtype: int64

In [33]:
seri.index # komutu ile serinin index bilgisine ulaşabiliriz.

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [34]:
seri.keys # komutu ile serinin key değerlerine ve onlara karşılık gelen value değerlerine erişebiliriz.

<bound method Series.keys of reg     145
loj     170
cart    187
rf      163
dtype: int64>

In [35]:
list(seri.items()) # seri üzerindeki tüm key ve value değerlerini ayrı ayrı görmek istersek bu çevirme işlemine ihtiyacımız olacaktır.

[('reg', 145), ('loj', 170), ('cart', 187), ('rf', 163)]

In [36]:
seri.values # komutu ile serinin value bilgilerine ulaşabilriz.

array([145, 170, 187, 163], dtype=int64)

## Eleman Sorgulama

In [37]:
"reg" in seri # sorgusu ile seri ismindeki seri yapısının içerisinde reg'in olup olmadığını kontrol eder.

True

In [38]:
"regg" in seri

False

## Fancy ile Eleman Seçme

In [39]:
seri[["rf", "cart"]]

rf      163
cart    187
dtype: int64

In [41]:
seri["rf"] = 168 # kod satırı ile rf'nin içerisindeki değeri değiştirebiliriz.
seri["rf"]

168

## Slice ile Eleman Seçme

In [42]:
seri["reg" : "rf"]

reg     145
loj     170
cart    187
rf      168
dtype: int64

## DataFrame Oluşturma

* DataFrame: yapısal bir veri tipidir. excel'e benzer yapıdadır.
* Peki NumPy varken neden bunlara ihtiyaç duyuluyor? 
  
  => NumPy fixed type özelliğe sahiptir, yani içerisinde tek bir veri tipinde değerler tutabilir. Kendi içerisinde kategorik ve sürekli değişkenler ile
     işlemler yapması hiç de kolay değildir. Çok zorlama yöntemler yaparak kullanmak mümkündür. Fakat ileri seviye veri manipülasyonlarına izin veremiyor.

In [47]:
list = [19, 37, 54, 54, 73, 91]
list

[19, 37, 54, 54, 73, 91]

In [48]:
pd.DataFrame(list)

0
0  19
1  37
2  54
3  54
4  73
5  91

In [49]:
pd.DataFrame(list, columns = ["baslik"]) # columns etiketi ile isimlendirme yapabiliriz.

baslik
0      19
1      37
2      54
3      54
4      73
5      91

* İki ve daha fazla değişken kullanarak bir DataFrame oluşturmak istersek;

In [50]:
import numpy as np
m = np.arange(1, 10).reshape(3, 3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
pd.DataFrame(m, columns = ["degisken1", "degisken2", "degisken3"])

degisken1  degisken2  degisken3
0          1          2          3
1          4          5          6
2          7          8          9

## DataFrame İsimlendirme

In [53]:
df = pd.DataFrame(m, columns = ["degisken1", "degisken2", "degisken3"])
df

degisken1  degisken2  degisken3
0          1          2          3
1          4          5          6
2          7          8          9

In [56]:
df.columns

Index(['degisken1', 'degisken2', 'degisken3'], dtype='object')

In [58]:
df.columns = ("var1", "var2", "var3")
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [59]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [60]:
type(df) # tip bilgisini döndürür.

pandas.core.frame.DataFrame

In [63]:
df.axes # index bilgisi (satır - sütün) verir.

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [64]:
df.shape # boyut bilgisi verir.

(3, 3)

In [65]:
df.ndim # df'nin boyutunu gösterir, df'ler ile çalışırken bu değer hep 2 çıkacaktır.

2

In [66]:
df.size # eleman sayısı hakkında bilgi verir

9

In [67]:
df.values # bu komut ile df içerisinden sadece value kısmını çekerek bir numpy array'i haline döndürür ve bizlere getirir.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
type(df.values) #sadece value kısmını aldığımız için tip olarak numpy array'i bilgisi alırız.

numpy.ndarray

In [69]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [70]:
df.tail(1)

var1  var2  var3
2     7     8     9

## DataFrame Eleman İşlemleri

* 3 tane NumPy array'i oluşturalım ve sözlük yapısı ile bu array'leri birleştirelim;

In [73]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [74]:
sozluk = {"var1" : s1, "var2" : s2, "var3" : s3}
sozluk

{'var1': array([7, 7, 4, 3, 5]),
 'var2': array([9, 0, 8, 4, 8]),
 'var3': array([6, 8, 5, 7, 9])}

* Oluşturduğumuz sözlük yapısını df'ye çevirelim;

In [83]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     7     9     6
1     7     0     8
2     4     8     5
3     3     4     7
4     5     8     9

In [84]:
df[0:3]

var1  var2  var3
0     7     9     6
1     7     0     8
2     4     8     5

In [86]:
df = pd.DataFrame(sozluk, index = ["a", "b", "c", "d", "e"])
df

var1  var2  var3
a     7     9     6
b     7     0     8
c     4     8     5
d     3     4     7
e     5     8     9

In [87]:
df["a":"c"]

var1  var2  var3
a     7     9     6
b     7     0     8
c     4     8     5

* Bu noktada şuna dikkat çekmek istiyorum; index işlemlerini eğer ki default olarak kullanıyorsak 0'dan başlayarak gelecektir, dolayısıyla biz 0:3'e kadar 
  olan kısmı istersek 0, 1 ve 2 geleceği için 3. indiste olanları göremeyiz. **Fakat** string indexleme de bu tarz bir durum olmadığı için a:c'ye kadar 
  dediğimizde a, b ve c gelecektir. 

# Index Silme İşlemi

In [88]:
df.drop("a", axis = 0) # axis değeri verme sebebimiz satıra görme silme işlemi yapacağımızı belirtmek içindir.

var1  var2  var3
b     7     0     8
c     4     8     5
d     3     4     7
e     5     8     9

In [89]:
df

var1  var2  var3
a     7     9     6
b     7     0     8
c     4     8     5
d     3     4     7
e     5     8     9

* Yukarıdaki çıktıda da gördüğümüz gibi biz "a" satırını drop etmemize rağmen halen daha df'in içerisinde var. Eğer ki "a" satırını kalıcı olarak drop
  etmek istiyorsak inplace = True eklemesini yapmamız gerekiyor;

In [91]:
df.drop("a", axis = 0, inplace = True)

In [92]:
df

var1  var2  var3
b     7     0     8
c     4     8     5
d     3     4     7
e     5     8     9

* Yeniden atama işlemi yapmadan inplace'i kullanarak yaptığımız değişiklikleri kalıcı hale getirebiliriz.

* df içerisinden tek bir satır değil de birden fazla satır silmek istersek ne yapmalıyız? Burada da devreye **fancy** girmektedir. facny kelime karşılığı
  olarak da fantastik demektir. Şu şekilde bu sorunu çözebiliriz;

In [93]:
l = ["b", "d"]

In [94]:
df.drop(l, axis = 0, inplace = True)

In [95]:
df

var1  var2  var3
c     4     8     5
e     5     8     9

## Değişkenler ile İşlemleri

In [96]:
"var1" in df

True

In [101]:
l = ["var1", "var22", "var3", "var"] # bu iki değişkenin df içerisinde var olup olmadığını sorgulayalım;

In [100]:
for i in l:
    print (i in df)

True
False
True
False


* Var olan df'nin içerisine bir değişken oluşturmak için (var4'ü oluştururken var1 * var3 değeri ile oluşuralım);

In [103]:
df["var4"] = df["var1"] * df["var3"] 

In [104]:
df

var1  var2  var3  var4
c     4     8     5    20
e     5     8     9    45

* Normalde df[] yazdığımız zaman bu yazımdan anlaşılan; df'in içerisine erişileceğidir ama eğer ki df'in içerisine yazılı olan string değişkenler 
  arasında yok ise bu şu şekilde algılanır; yeni değişken olarak ekle.

## Değişken Silme İşlemi

In [106]:
df.drop("var1", axis = 1, inplace = True)

In [107]:
df

var2  var3  var4
c     8     5    20
e     8     9    45

* fancy ile birden fazla değişkeni tek seferde silme işlemini burada da uygulayabiliriz.

In [108]:
l = ["var2", "var3"]

In [109]:
df.drop(l, axis = 1, inplace = True)

In [110]:
df

var4
c    20
e    45